# Generated by Django 6.0.5 on 2026-06-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('commerce', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(max_length=255)),
                ('card', models.CharField(max_length=50)),
                ('authorization', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('transactionType', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Categorized', 'Categorized'), ('Uncategorized', 'Uncategorized'), ('Pending', 'Pending')], default='Uncategorized', max_length=20)),
                ('json', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.budgetsmodel')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.subcategoriesmodel')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
    ]
