# Generated by Django 5.2.14 on 2026-06-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerce', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('card_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Categorized', 'Categorized')], default='Uncategorized', max_length=20)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgets.budget')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budgets.section')),
            ],
        ),
    ]
