# Generated by Django 6.0.6 on 2026-07-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='authorization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='status',
            field=models.CharField(choices=[('Categorized', 'Categorized'), ('Uncategorized', 'Uncategorized'), ('Pending', 'Pending'), ('Mock', 'Mock')], default='Uncategorized', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='transactionType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
