# Generated by Django 6.0.6 on 2026-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactionsmodel_authorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
