# Generated by Django 6.1.1 on 2026-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionsmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='status',
            field=models.CharField(choices=[('Categorized', 'Categorized'), ('Uncategorized', 'Uncategorized'), ('Pending', 'Pending'), ('Mock', 'Mock'), ('Suggested', 'Suggested')], default='Uncategorized', max_length=20),
        ),
    ]
