# Generated by Django 6.1.1 on 2026-09-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='status',
            field=models.CharField(choices=[('Categorized', 'Categorized'), ('Uncategorized', 'Uncategorized'), ('Pending', 'Pending'), ('Placeholder', 'Placeholder'), ('Suggested', 'Suggested')], default='Uncategorized', max_length=20),
        ),
    ]
