# Generated by Django 6.1.1 on 2026-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_transactionsmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionsmodel",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
