services:
  service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: capital-focus-service
    ports:
      - "9003:8080"
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
    networks:
      - rklan

networks:
  rklan:
    external: true