# Generated by Django 6.0.5 on 2026-06-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sectionsmodel',
            table='sections',
        ),
    ]
