# Generated by Django 6.0.5 on 2026-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_sectionsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsmodel',
            name='projection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
