# Generated by Django 6.0.5 on 2026-06-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('sections', '0003_alter_sectionsmodel_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionsmodel',
            name='categories',
        ),
        migrations.AddField(
            model_name='sectionsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='categories.categoriesmodel'),
        ),
    ]
