# Generated by Django 6.0.5 on 2026-06-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budgetsmodel_projection'),
        ('sections', '0004_remove_sectionsmodel_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsmodel',
            name='budgets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budgets.budgetsmodel'),
        ),
    ]
