# Generated by Django 6.0.5 on 2026-06-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsmodel',
            options={'verbose_name_plural': 'Budgets'},
        ),
    ]
